### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by karimkohel** [PrecisionGazeMouse/PGMWebsite#1]
i have been checking the website for the past weeks and it seems that it's down with no intention of getting it back up, is there a way for users to install the software while the website is down? the installer always fetches from the website so it's broken at the moment. or if you can upload the executable for win64 

@nash8350

**Comment by nash8350** [comment]
I renewed the domain for one more year. I don' think I will after that because I'm hoping we can find a new maintainer. Alternatively, you can download the installer directly from here https://github.com/PrecisionGazeMouse/PGMWebsite/tree/master/static/install

**Comment by karimkohel** [comment]
Thank you for your help, and I'm glad you had fun working on this project.
